---
name: alpine-clang-c++14
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check
      env:
        CXXFLAGS: "-std=c++14"
    container:
      image: takei/libyu-dev:alpine3-clang
