name: alpine3-clang
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: takei/libyu-dev:alpine3-clang
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make CXX=clang++
    - name: make check
      run: make check CXX=clang++
