name: alpine3-gcc -std=23
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: takei/libyu-dev:alpine3-gcc
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXX=g++
