---
'on':
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update -y && sudo apt-get install -y doxygen graphviz
      - name: Generate Doxygen documentation
        run: doxygen
      - name: Upload Doxygen documentation as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html/

  deploy:
    name: deploy
    permissions:
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

