name: gcc
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        image: [gcc:4, gcc:5, gcc:6, gcc:7, gcc:8, gcc:9, gcc:10, gcc:11, gcc:12, gcc:13]
        cxxflags: ["", -std=c++11, -std=c++14, -std=c++17, -std=c++20, -std=c++23]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXXFLAGS=${{ matrix.cxxflags }}

