name: gcc
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        gcc_version: [5, 6, 7, 8, 9, 10, 11, 12, 13]
    runs-on: ubuntu-latest
    container:
      image: gcc:${{ matrix.gcc_version }}
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check
