---
name: gcc12-c++17
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check CXXFLAGS='-std=c++17'
    container:
      image: gcc:12
