name: gcc-13 -std=11
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:13
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXXFLAGS=-std=c++11
