name: gcc-12 c++14
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:12
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check CXXFLAGS=-std=c++14
