---
name: gcc11-c++23
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check
      env:
        CXXFLAGS: "-std=c++23"
    container:
      image: gcc:11
