name: gcc-11 default
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:11
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check CXXFLAGS=
