---
name: gcc10-c++11
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check
      env:
        CXXFLAGS: "-std=c++11"
    container:
      image: gcc:10
