name: gcc-10 default
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:10
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXXFLAGS=
