name: gcc-4 c++11
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: takei/libyu-dev:gcc4
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXXFLAGS=-std=c++11
