  name: gcc-6 c++17
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: takei/libyu-dev:gcc6
      steps:
      - uses: actions/checkout@v3
      - name: make check
        run: make check CXXFLAGS=-std=6
