name: gcc-6 -std=20
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:6
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXXFLAGS=-std=c++20
