  name: gcc-8 c++14
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: gcc:8
      steps:
      - uses: actions/checkout@v3
      - name: make check
        run: make check CXXFLAGS=-std=8
