name: gcc9
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:9
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
