name: macos-11-gcc -std=c++11
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXX=g++ CXXFLAGS=-std=c++11
