name: macos-11 -std=c++20
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check  CXXFLAGS=-std=c++20
