name: macos-12-gcc -std=c++20
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXX=g++ CXXFLAGS=-std=c++20
