---
name: macos14-c++20
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: make check
      env:
        CXXFLAGS: "-std=c++20"
