name: macos-12 -std=c++11
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check  CXXFLAGS=-std=c++11
