name: macos-13-clang -std=14
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXX=clang++ -std=14
