name: macos-12-clang -std=c++17
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make check CXX=clang++ CXXFLAGS=-std=c++17
